apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-local-video-player
  annotations:
    kubernetes.io/ingress.class: nginx
    #kubernetes.io/ingress.class: "traefik"
    #kubernetes.io/ingress.class: public
    #nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - quangtuan.me
    secretName: quangtuan-me-tls
  rules:
    - host: quangtuan.me
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: local-video-player-svc
                port:
                  number: 80
